[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
namespace_packages = true
mypy_path = "./googleapi"  # Updated to match your application root

[tool.isort]
known_first_party = "googleapi"  # Set your module name here
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.ruff]
# General settings
extend-exclude = ["googleapi/tests"]

lint.select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]

lint.ignore = [
    "E501",  # Line too long, handled by Black
    "B008",  # Function calls in argument defaults
    "C901",  # Too complex
    "E731",  # Using lambda instead of def
]

[tool.ruff.lint.per-file-ignores]
# Allow dict() usage in tests, if applicable
"googleapi/tests/*.py" = ["C408"]
