# generated by datamodel-codegen:
#   filename:  calendar_response.json
#   timestamp: 2024-12-14T12:37:03+00:00

from __future__ import annotations

from typing import List, TypedDict


class Name(TypedDict):
    fullName: str
    familyName: str
    givenName: str
    displayName: str


class UserModel(TypedDict):
    id: str
    primaryEmail: str
    password: str
    hashFunction: str
    isAdmin: str
    isDelegatedAdmin: str
    agreedToTerms: str
    suspended: str
    changePasswordAtNextLogin: str
    ipWhitelisted: str
    name: Name
    kind: str
    etag: str
    emails: str
    externalIds: str
    relations: str
    aliases: List[str]
    isMailboxSetup: str
    customerId: str
    addresses: str
    organizations: str
    lastLoginTime: str
    phones: str
    suspensionReason: str
    thumbnailPhotoUrl: str
    languages: str
    posixAccounts: str
    creationTime: str
    nonEditableAliases: List[str]
    sshPublicKeys: str
    notes: str
    websites: str
    locations: str
    includeInGlobalAddressList: str
    keywords: str
    deletionTime: str
    gender: str
    thumbnailPhotoEtag: str
    ims: str
    customSchemas: str
    isEnrolledIn2Sv: str
    isEnforcedIn2Sv: str
    archived: str
    orgUnitPath: str
    recoveryEmail: str
    recoveryPhone: str


class UserListModel(TypedDict):
    kind: str
    trigger_event: str
    etag: str
    users: List[UserModel]
    nextPageToken: str


class MemberModel(TypedDict):
    kind: str
    email: str
    role: str
    etag: str
    type: str
    status: str
    delivery_settings: str
    id: str


class MemberListModel(TypedDict):
    kind: str
    etag: str
    members: List[MemberModel]
    nextPageToken: str


class GroupModel(TypedDict):
    id: str
    email: str
    name: str
    description: str
    adminCreated: str
    directMembersCount: str
    kind: str
    etag: str
    aliases: List[str]
    nonEditableAliases: List[str]


class GroupListModel(TypedDict):
    kind: str
    etag: str
    groups: List[GroupModel]
    nextPageToken: str
