# generated by datamodel-codegen:
#   filename:  calendar_response.json
#   timestamp: 2024-12-15T16:46:40+00:00

from __future__ import annotations

from typing import TypedDict, List


class Capabilities(TypedDict):
    canAddChildren: str
    canComment: str
    canCopy: str
    canDeleteDrive: str
    canDownload: str
    canEdit: str
    canListChildren: str
    canManageMembers: str
    canReadRevisions: str
    canRename: str
    canRenameDrive: str
    canChangeDriveBackground: str
    canShare: str
    canChangeCopyRequiresWriterPermissionRestriction: str
    canChangeDomainUsersOnlyRestriction: str
    canChangeDriveMembersOnlyRestriction: str
    canChangeSharingFoldersRequiresOrganizerPermissionRestriction: str
    canResetDriveRestrictions: str
    canDeleteChildren: str
    canTrashChildren: str


class BackgroundImageFile(TypedDict):
    id: str
    xCoordinate: str
    yCoordinate: str
    width: str


class Restrictions(TypedDict):
    copyRequiresWriterPermission: str
    domainUsersOnly: str
    driveMembersOnly: str
    adminManagedRestrictions: str
    sharingFoldersRequiresOrganizerPermission: str


class DriveModel(TypedDict):
    id: str
    name: str
    colorRgb: str
    kind: str
    backgroundImageLink: str
    capabilities: Capabilities
    themeId: str
    backgroundImageFile: BackgroundImageFile
    createdTime: str
    hidden: str
    restrictions: Restrictions
    orgUnitId: str


class DrivesModel(TypedDict):
    nextPageToken: str
    kind: str
    drives: List[DriveModel]
