name: Auto Tag Version

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies to parse pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      # Extract version from pyproject.toml
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Check if the tag already exists
      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="v${{ steps.get_version.outputs.VERSION }}"
          if git tag --list | grep -q "^$TAG$"; then
            echo "Tag $TAG already exists"
            echo "TAG_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist"
            echo "TAG_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      # Create and push the tag if it doesn't exist
      - name: Create and push tag
        if: steps.check_tag.outputs.TAG_EXISTS == 'false'
        run: |
          TAG="v${{ steps.get_version.outputs.VERSION }}"
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}